package com.utn.reglas;
import com.utn.model.Metodologia;
import com.utn.reglas.Respuesta;

// regla para la condicion Maximizar ROE
rule "Maximizar ROE"
	
    when
        meto: Metodologia(nombre.equals("Ricardo"));
        resp: Respuesta()
    then 
    	meto.setNombre("xxx");
    	resp.setValor("AAAA");
    	resp.agregar("gato");
end

// regla para la condicion Minimizar nivel de deuda
rule "Minimizar dueda"
	
    when
        
    then 
    	
end

// regla para la condicion Márgenes consistentemente crecientes
rule "Margenes consistentemente crecientes"
	
    when
        
    then 
    	
end

// regla para la condicion Longevidad
rule "Longevidad"
	
    when
        
    then 
    	
end