package com.utn.reglas;
import com.utn.model.Metodologia;
import com.utn.reglas.Respuesta;
import com.utn.dao.EmpresaDAO;

// regla para la condicion Maximizar ROE
// Busca la empresa que sumando los ROE de todas sus cuentas sea la mejor
rule "Maximizar ROE"
	
    when
    	metodologia: Metodologia(metodologia.getListaCondiciones().contains("Maximizar ROE"));
        respuesta: Respuesta();
        
    then 
    	EmpresaDAO empresaDAO = new EmpresaDAO();
    	respuesta.agregar("Maximizar ROE",empresaDAO.getEmpresaMejorROE());
    	
end

// regla para la condicion Minimizar nivel de deuda
rule "Minimizar dueda"
	
    when
        
    then 
    	
end

// regla para la condicion Márgenes consistentemente crecientes
rule "Margenes consistentemente crecientes"
	
    when
        
    then 
    	
end

// regla para la condicion Longevidad
// Busca la empreza mas antigua entre todas y ademas q como minimo pasen los 10 años
rule "Longevidad"
	
    when
    	metodologia: Metodologia(metodologia.getListaCondiciones().contains("Longevidad"));
        respuesta: Respuesta();
        
    then 
    	EmpresaDAO empresaDAO = new EmpresaDAO();
    	respuesta.agregar("Longevidad",empresaDAO.getEmpresaMasAntigua());
end